### general ###
keep-open=yes
osd-font-size=32
alang=jpn
slang=eng
sub-ass-override=no
sub-margin-y=35

### Profiles ###

[baseline]
profile-desc="Default Profile"

[normal]
profile-desc="Modern Override"
sub-font='Gandhi Sans'
sub-color='#EBEBEB'
sub-font-size=48
sub-shadow-color='#000000'
sub-bold=yes
sub-border-size=3
sub-blur=0.25
sub-pos=100
sub-shadow-offset=1.5


[boomer]
profile-desc="Boomer Mode"
sub-font='Arial Narrow'
sub-font-size=42
sub-bold
sub-color='#FFFF00'
sub-border-color='#000000'
sub-shadow-offset=0
sub-border-size=4.5
sub-blur=0
sub-pos=100

[NewCinema]
profile-desc="AAA Japanese Video Game"
sub-font='NewCinemaAStd-D'
sub-font-size=36
sub-color='#FFFF00'
sub-border-color='#000000'
sub-border-size=3.5
sub-blur=2.5
sub-pos=100


